### ISSUE TITLE
/r/investment welcomes nano_tipper

### ISSUE THREAD

**Issue by superluminal300** [danhitchcock/nano_tipper_z#55]
Hi, I’m the primary moderator of /r/investment and I welcome nano_tipper to be a full part of our subreddit. Please add us to the friendly sub list.

**Comment by danhitchcock** [comment]
Hi superluminal -- that's great to hear!
You actually have total control of the bot on your subreddit. Send a message to /u/nano_tipper_z
`subreddit investment activate`

You can also change the minimum tips, or shrink the response size. Send me a dm on reddit (/u/zily88) if you need any more help.
