### ISSUE TITLE
Error Description in Error message

### ISSUE THREAD

**Issue by ThunderFD** [danhitchcock/nano_tipper_z#58]
I have seen a thread on Reddit now where someone was just tipping a lot of people but always got error code 160. 

Which means he didn’t have enough balance - imo the bot should specify this in the reply so that people aren’t too confused...

**Comment by danhitchcock** [comment]
Hi, this feature is part of its "tiny" response, so that the subreddit isn't littered with bulky messages, especially when users keep using the bot incorrectly. My thought was that the error codes are easy enough to find, but maybe I can add a short message in addition to the error code.
