### ISSUE TITLE
Make nano_tipper send PM when funds are loaded

### ISSUE THREAD

**Issue by superluminal300** [danhitchcock/nano_tipper_z#60]
Nano_tipper currently does not send a PM when funds are loaded from an external wallet.

Recommend having nano_tipper send the user a PM when funds are transferred from external wallet into the tip wallet.

**Comment by danhitchcock** [comment]
I unfortunately won't be able to implement this since I don't have a good way to throttle incoming transactions and the subsequent PMs that are generated.
