### ISSUE TITLE
Use the same message thread

### ISSUE THREAD

**Issue by oojacoboo** [danhitchcock/nano_tipper_z#61]
Just decided to setup the `u/nano_tipper` wallet with a balance for tipping.  Unfortunately, I was greeted with a slew of threads from the bot, commands issued through any of the threads just spawn new threads.  Then you have to go through all of them to see more details, etc.  They end up polluting your message thread history as well.

Please fix the bot to share the same message thread.  The new threads are very frustrating.

**Comment by danhitchcock** [comment]
I might be able to add a reply field in the messages sql table, thus it will reply to PMs instead of generating new ones. I'll investigate this.
